<?php if($block->getData('id')): ?>

  <?php if($block->getData('include_css') && $block->getData('include_css') == 'yes'): ?>
    <style>
      .videoWrapper {
        position: relative;
        padding-bottom: 56.25%; /* 16:9 */
        padding-top: 25px;
        height: 0;      
      }
      .videoWrapper iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
      }
    </style>
  <?php endif; ?>

  <div class="videoWrapper">
    <iframe 
      width="560" 
      height="315" 
      src="https://www.youtube.com/embed/<?php echo $block->getData('id'); ?>" 
      frameborder="0" 
      allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>      
    </iframe>
  </div>
<?php endif; ?>
